name: grafana
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions:
  id-token: write
  contents: read
 
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: 20906787-3b17-4ab3-bcc9-e3be7eb3d4a5
          tenant-id: fd2d14ef-5afe-49fc-90d8-c542641e9eae
          subscription-id: b2f35947-820e-42de-96c7-8905c7b6a259
      - name: terraform init
        run: terraform init
        working-directory: environment\dev
      - name: terraform init
        run: terraform init
        working-directory: environment\dev
  
      - name: terraform plan
        run: terraform plan 
        working-directory: environment\dev

  deploy:
    name: terraform apply
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    environment: dev
    steps: 
    - name: Checkout
      uses: actions/checkout@v5.0.0
     
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 20906787-3b17-4ab3-bcc9-e3be7eb3d4a5
        tenant-id: fd2d14ef-5afe-49fc-90d8-c542641e9eae
        subscription-id: b2f35947-820e-42de-96c7-8905c7b6a259
    
    - name: terraform init
      run: terraform init
      working-directory: environment\dev   
    - name: terraform apply 
      run: terraform apply --auto-approve
      working-directory: environment\dev
  
  

        
         

          
